### ISSUE TITLE
GitHub Actions integrations

### ISSUE THREAD

**Issue by gullabi** [Galtea-AI/galtea-docs#12]
We need to create a basic document which shows with examples how to setup github actions with Galtea. 

Here are some new examples:
https://docs.confident-ai.com/guides/guides-regression-testing-in-cicd
https://docs.giskard.ai/en/stable/integrations/cicd/pipeline.html

* The version and test name needs to be accessible with their name (not id)
* Their product version does mock inference based on the test_case
* Whenever there is a new version, it needs to call a specific test to run for a given list of metrics.

## Proposal of Dende:

We would like to declare the whole setup and let Galtea create/replace/skip in our services.
For example, in a GitHub Action this could look like:

```yaml
- name: Run Dende Evaluation
  run: |
    poetry install
    export GALTEA_API_KEY=${{ secrets.GALTEA_API_KEY }}
    export GALTEA_PRODUCT_ID=${{ secrets.GALTEA_PRODUCT_ID }}
    export GALTEA_VERSION_NAME=${{ secrets.SERVICE_NAME }}@${{ github.sha }}
    poetry run galtea run config/evaluation.yaml --version=$GALTEA_VERSION_NAME

```

Where `evaluation.yaml` is:

```yaml
galtea_api_key: # Leave empty to use GALTEA_API_KEY environment variable (recommended)

product:
  id: # Leave empty to use GALTEA_PRODUCT_ID environment variable (recommended)

version: # This could maybe come from the cli args: --version=$GALTEA_VERSION_NAME
  service_name: "demo-model"
  service_tag: "v1.0.2"

# get by name, create if not exists
test:
  name: "General Knowledge Quiz"
  type: "QUALITY"

model:
  outputs_file: "demo/model_outputs.json" # list of { test_case_id, actual_output }

test_cases:
  file: "demo/test_cases.json" # list of { test_case_id, input, expected_output, tag, context, ... }

metrics:
  - "accuracy_v0"

```
